/**
 * Build-time generator: public/avatar.jpg → pre-rendered ASCII avatar.
 *
 * Outputs (all committed; regenerated on every build via `prebuild`):
 *  - app/generated/ascii-avatar.ts        typed matrix consumed by the Hero card
 *  - public/ascii-avatar-dark.txt         plain-text static assets for mobile /
 *  - public/ascii-avatar-light.txt        degraded variants
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { decodeImage } from "./decode.mjs";
import { cropToSquare, imageToAscii } from "./core.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const SOURCE = path.join(root, "public", "avatar.jpg");
const TS_OUT = path.join(root, "app", "generated", "ascii-avatar.ts");
const TXT_OUT = (theme) => path.join(root, "public", `ascii-avatar-${theme}.txt`);

// 60 cols at charAspect 0.6 → 36 rows for the square crop, which renders as a
// square block in a line-height:1 monospace context (glyph width ≈ 0.6em).
const COLS = 60;
const CHAR_ASPECT = 0.6;

const image = cropToSquare(decodeImage(SOURCE));
const variants = {};
for (const theme of ["dark", "light"]) {
  const { lines, green, rows, cols } = imageToAscii(image, {
    theme,
    cols: COLS,
    charAspect: CHAR_ASPECT,
  });
  variants[theme] = { lines, green };
  variants.rows = rows;
  variants.cols = cols;
  fs.writeFileSync(TXT_OUT(theme), lines.join("\n") + "\n");
}

const ts = `// AUTO-GENERATED by scripts/ascii-avatar/generate.mjs — do not edit by hand.
// Source: public/avatar.jpg. Regenerate with \`npm run generate:ascii\`.

export type AsciiVariant = {
  lines: string[];
  /** Per-row [startCol, endCol) runs of terminal-green glyphs. */
  green: [number, number][][];
};

export type AsciiAvatar = {
  cols: number;
  rows: number;
  dark: AsciiVariant;
  light: AsciiVariant;
};

export const asciiAvatar: AsciiAvatar = ${JSON.stringify(
  {
    cols: variants.cols,
    rows: variants.rows,
    dark: variants.dark,
    light: variants.light,
  },
  null,
  2
)};
`;

fs.mkdirSync(path.dirname(TS_OUT), { recursive: true });
fs.writeFileSync(TS_OUT, ts);

console.log(
  `ascii-avatar: ${variants.cols}x${variants.rows} matrix → ${path.relative(root, TS_OUT)}, ` +
    `ascii-avatar-{dark,light}.txt`
);
